name: Docker

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build-docker-compose:
    name: Build
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
          working-directory: docker
    steps:

    - name: Curl Docker Compose
      run: sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

    - name: Grand Access to Docker Compose
      run: sudo chmod +x /usr/local/bin/docker-compose
    
    - name: Move Docker Compose
      run: sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

    - name: Build Docker Compose
      run: docker-compose build